name: Terraform Deploy

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION || 'eu-central-1' }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      #The backend.hcl file needs to be configured for the persistence and for the entire /dev folder - here it starts
      - name: Persistent - Terraform Init
        working-directory: envs/persistent
        run: |
          terraform init \
            -backend-config=backend.hcl \
            -backend-config="key=envs/persistent/terraform.tfstate"

      - name: Persistent - Terraform Plan
        working-directory: envs/persistent
        run: terraform plan

      - name: Persistent - Terraform Apply
        working-directory: envs/persistent
        run: terraform apply -auto-approve

      - name: Dev - Terraform Init
        working-directory: envs/dev
        run: |
          terraform init \
            -backend-config=backend.hcl \
            -backend-config="key=envs/dev/terraform.tfstate"

      #Here it ends, it is very important because the vpn.tf file cannot read the storage if it is not initialized

      - name: Dev - Terraform Plan
        working-directory: envs/dev
        run: terraform plan

      - name: Dev - Terraform Apply
        working-directory: envs/dev
        run: terraform apply -auto-approve
